#!/bin/bash

H1='Ingresa si quieres ingresar a metodologías ágiles (ingrese -a) o a metodologías tradicionales (ingrese -t)'
options=("-a" "-t" "Quit")
select opt in "${options[@]}"
do
  case $opt in 
    "-a")
      
      ;;
    "-t")
      
      ;;
    "Quit")
      break
      ;;
     *) echo "invalid option $REPLY";;
  esac
done

