#!/bin/bash

H1='Ingresa si quieres ingresar a metodologías ágiles (ingrese -a) o a metodologías tradicionales (ingrese -t)'
options=("-a" "-t" "Quit")
select opt in "${options[@]}"
do
  case $opt in 
    "-a")
      
      ;;
    "-t")
      
      ;;
    "Quit")
      break
      ;;
     *) echo "invalid option $REPLY";;
  esac
done

function_a()
{

echo "Bienvenido a la guía rápida de Agile, para continuar seleccione un tema:" 
optionsA = ("SCRUM", "X.P.", "Kanban", "Crystal")

select optA in ${optionsA[@]}"
do
  case $optA in
    "SCRUM")
      echo "Usted esta en la sección SCRUM, seleccione la opción que desea utilizar."
      ;;
     "X.P.")
      echo "Usted esta en la sección X.P., seleccione la opción que desea utilizar."
      ;;
     "Kanban")
      echo "Usted esta en la sección Kanban, seleccione la opción que desea utilizar."
      ;;
     "Crystal")
      echo "Usted esta en la sección Crystal, seleccione la opción que desea utilizar."
     

}

