#!/bin/bash

menu_p(){
  H1='Ingresa si quieres ingresar a metodologías ágiles (ingrese -a) o a metodologías tradicionales (ingrese -t)'
  options=("-a" "-t" "Salir")
  select opt in "${options[@]}"
  do
    case $opt in 
      "-a")
        function_a()

        ;;
      "-t")
        function_t()
        ;;
      "Salir")
        break
        ;;
       *) echo "opción inválida $REPLY";;
    esac
  done
}

# Agregar info en a
agregarinfoA() 
{
  echo $doc
  echo "Escribe la info que quieres agregar: "
  read info
  echo "$info" >> $doc
  echo "Información agregada correctamente"
  
  while true; do 
  echo "¿Quieres agregar mas información o regresar al menú?"
  echo "1. Agregar más info"
  echo "2. Regresar al menú"
  
  read choice
  case $choice in
    1)
        agregarinfoA() 
        ;;
      2)
        return
        ;;
      *)
        echo "Opción inválida"
        ;;
    esac
  done
}


# Ver la info de a
verinfo()
{
  cat $doc
  while true; do
      echo "Presiona cualquier tecla para regresar al menú"
      read choice

      return
    done
}


# Borrar la info de a
borrarinfo()
{
  echo $doc
  echo "Escribe que información quieres borrar: "
  read term
  grep -i "$term"  $doc
  echo "Escribe el numero de linea que quieres borrar: "
  read numbers
  sed -i "${numbers}d" $doc
  echo "Se borrarán las lineas que seleccionaste"
  
  while true; do
    echo "¿Quieres borrar mas información o regresar al menú?"
    echo "1. Borrar info"
    echo "2. Regresar al menú"

    read choice

    case $choice in
      1)
        borrarinfo()
        ;;
      2)
        return
        ;;
      *)
        echo "Opción inválida"
        ;;
    esac
  done
}


# Buscar la info de a
buscarinfo()
{
  echo $doc
  echo "Escribe que información quieres bucsar: "
  read term
  grep -i "$term"  $doc
  while true; do 
  echo "¿Quieres buscar mas información o regresar al menú?"
  echo "1. Buscar más info"
  echo "2. Regresar al menú"
  
  read choice
  case $choice in
    1)
        buscarinfo() 
        ;;
      2)
        return
        ;;
      *)
        echo "Opción inválida"
        ;;
    esac
  done
}


menu() {
  while true; do
    informacion = "Escribe que quieres hacer: "
    opciones = ("Agregar info", "Buscar info", "Borar info", "Ver info")
    select opc in "${opciones[@]}"
    do 
      case $opc in
        "Agregar info")
          echo "Seleccionaste agregar info"
          agregarinfo $doc
          ;;
        "Buscar info")
          echo "Seleccionaste buscar info"
          buscarinfo $doc
          ;;
        "Borrar info")
          echo "Seleccionaste borrar info"
          borrarinfo $doc
          ;;
        "Ver info")
          echo "Seleccionaste ver info"
          ver info $doc
         "Salir"
            break
            ;;
         *) echo "Opción invalida"
         ;;
        esac 
      done
} 


function_a()
{
echo "Bienvenido a la guía rápida de Agile, para continuar seleccione un tema:" 
optionsA = ("SCRUM", "X.P.", "Kanban", "Crystal", "Main Menu")

select optA in ${optionsA[@]}"
do
  case $optA in
    "SCRUM")
      echo "Usted esta en la sección SCRUM, seleccione la opción que desea utilizar."
      menu SCRUM.inf
      ;;
     "X.P.")
      echo "Usted esta en la sección X.P., seleccione la opción que desea utilizar."
      menu XP.inf
      ;;
     "Kanban")
      echo "Usted esta en la sección Kanban, seleccione la opción que desea utilizar."
      menu Kanban.inf
      ;;
     "Crystal")
      echo "Usted esta en la sección Crystal, seleccione la opción que desea utilizar."
      menu Crystal.inf
      ;;
     "Main Menu"
      menu_p()
      ;;
}

function_t()
{
echo "Bienvenido a la guía rápida de Agile, para continuar seleccione un tema:" 
optionsA = ( "Cascada", "Espiral", "ModeloV", "Main Menu")

select optA in ${optionsA[@]}"
do
  case $optA in
    "Cascada")
      echo "Usted esta en la sección Cascada, seleccione la opción que desea utilizar."
      menu Cascada.inf
      ;;
     "Espiral")
      echo "Usted esta en la sección Espiral, seleccione la opción que desea utilizar."
      menu Espiral.inf
      ;;
     "ModeloV")
      echo "Usted esta en la sección Modelo V, seleccione la opción que desea utilizar."
      menu ModeloV.inf
      ;;
     "Main Menu")
      menu_p()
      ;;
}

