name: Docker Image CI

on:
  push:

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Check out code
      run: docker image build -t proyetico.sh .
